language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - AWS_SECRET_ACCESS_KEY=fake_key AWS_ACCESS_KEY_ID=fake_id

install:
  - pip install tox

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)